[packages]
pacman = [
  "7zip",
  "aria2",
  "base",
  "base-devel",
  "bash-completion",
  "bat",
  "btop",
  "discord",
  "dust",
  "eza",
  "fd",
  "feh",
  "firefox",
  "fuse2",
  "fzf",
  "gdb",
  "gimp",
  "git",
  "helix",
  "i3-wm",
  "i3lock",
  "imagemagick",
  "jdk-openjdk",
  "just",
  "kitty",
  "lazygit",
  "less",
  "lib32-nvidia-utils",
  "linux",
  "linux-firmware",
  "maim",
  "man-db",
  "mangohud",
  "marksman",
  "mpc",
  "mpd",
  "mpv",
  "networkmanager",
  "nodejs",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "nushell",
  "nvidia",
  "obs-studio",
  "openssh",
  "pacman-contrib",
  "pass",
  "picom",
  "pipewire-jack",
  "polybar",
  "prismlauncher",
  "pulsemixer",
  "qbittorrent",
  "qt6ct",
  "reflector",
  "ripgrep",
  "rustup",
  "sccache",
  "steam",
  "strace",
  "taplo-cli",
  "tealdeer",
  "tesseract-data-afr",
  "tinymist",
  "tmux",
  "tokei",
  "trash-cli",
  "woff2-font-awesome",
  "ttf-jetbrains-mono-nerd",
  "typst",
  "udiskie",
  "unzip",
  "uv",
  "wine-mono",
  "xclip",
  "xdotool",
  "xorg-server",
  "xorg-xinit",
  "xorg-xwininfo",
  "yazi",
  "yt-dlp",
  "zathura",
  "zathura-pdf-mupdf",
  "zig",
  "zip",
  "zls",
]

paru = [
  "aseprite",
  "catppuccin-cursors-mocha",
  "catppuccin-gtk-theme-mocha",
  "git-credential-manager-bin",
  "glsl_analyzer",
  "gzdoom-bin",
  "paru-bin",
  "paru-bin-debug",
  "vesktop-bin",
  "zmusic-bin",
]
