mgr.prepend_keymap = [
  { desc = "Goto ~/.dots", on = [ "g", ".", ], run = "cd ~/.dots" },
  { desc = "Goto ~/Downloads", on = [ "g", "D", ], run = "cd ~/Downloads" },
  { desc = "Goto ~/Documents", on = [ "g", "d", ], run = "cd ~/Documents" },
  { desc = "Goto ~/Pictures", on = [ "g", "p", ], run = "cd ~/Pictures" },
  { desc = "Goto ~/Music", on = [ "g", "m", ], run = "cd ~/Music" },
  { desc = "Goto ~/Videos", on = [ "g", "v", ], run = "cd ~/Videos" },
  { desc = "Goto ~/.config", on = [ "g", "C", ], run = "cd ~/.config" },
  { desc = "Goto ~/.cache", on = [ "g", "c", ], run = "cd ~/.cache" },
  { desc = "Goto ~/.local", on = [ "g", "l", ], run = "cd ~/.local" },
  { desc = "Goto /", on = [ "g", "r", ], run = "cd /" },
  { desc = "Goto /run/media", on = [ "g", "M", ], run = "cd /run/media" },
  { desc = "Set background", on = [ "b", ], run = "shell --confirm 'setbg \"$0\" || :'" },
]
