theme = "catppuccin_mocha"

[editor]
cursorline = true
line-number = "relative"
bufferline = "multiple"

smart-tab.enable = false
auto-pairs = false
auto-format = false

lsp.auto-signature-help = false
lsp.snippets = false
completion-timeout = 5     # Show completions instantly
completion-trigger-len = 1 # Show completions after typing 1 character

end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "hint"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false            # Show hidden files
deduplicate-links = false # Don't remove links

[keys.insert]
C-c = "normal_mode"

# Emacs
C-a = "goto_line_start"
C-e = "goto_line_end_newline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-c = ["collapse_selection", "keep_primary_selection"]

space.u = ":reset-diff-change" # Reset hunk

# Move selection
C-left = "unindent"
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-right = "indent"
C-h = "unindent"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-l = "indent"

[keys.select]
C-c = "normal_mode"

space.u = ":reset-diff-change" # Reset hunk

# Move selection
C-left = "unindent"
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-right = "indent"
C-h = "unindent"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-l = "indent"

# Toggle options
[keys.normal.space.t]
n = ":toggle line-number absolute relative"
w = ":toggle soft-wrap.enable"
s = ":toggle whitespace.render none all"
h = ":toggle lsp.display-inlay-hints"
c = ":toggle search.smart-case"
[keys.select.space.t]
n = ":toggle line-number absolute relative"
w = ":toggle soft-wrap.enable"
s = ":toggle whitespace.render none all"
h = ":toggle lsp.display-inlay-hints"
c = ":toggle search.smart-case"
